(IF (AND (NOT (Trade_Buy_OnBar_H1)
         )
     (AndS Singapore_Swing S_SELL P_H1)
    )
 (START)
 (SELL)
)
(IF (AND (NOT (Trade_Sell_OnBar_H1)
         )
     (AndS Singapore_Swing S_BUY P_H1)
    )
 (START)
 (BUY)
)
