(IF (AND (NOT (Fractal_Up_Zone)
         )
     (AndS UPFRACTAL S_ABOVE P_H1 )
    )
 (START)
 (BUY)
)
(IF (AND (NOT (Fractal_Down_Zone)
         )
     (AndS DOWNFRACTAL S_BELOW P_H1)
    )
 (START)
 (SELL)
)
