(IF (AND (Gap_Down_D1)
     (AndS BAR S_BULL P_H1)
     (AndS CLOSE S_BELOW P_H1)
    )
 (START)
 (BUY)
)
(IF (AND (Gap_Up_D1)
     (AndS BAR S_BEAR P_H1)
     (AndS CLOSE S_ABOVE P_H1 )
    )
 (START)
 (SELL)
)
(IF (OR (AndS CLOSE S_CROSS_DOWN P_D1)
     (AndS CLOSE S_CROSS_UP P_D1)
    )
 (CLOSE_BUY)
 (CLOSE_SELL)
)
