(IF (AndPS Force S_CROSS_UP P_H1)
 (START)
 (IF (AND (>= T_PROFITSELL 10)
      (> T_SELLNBRTRADE 2)
     )
  (CLOSE_SELL)
 )
)
(IF (AndPS Force S_CROSS_DOWN P_H1 )
 (START)
 (IF (AND (>= T_PROFITBUY 10)
      (> T_BUYNBRTRADE 2)
     )
  (CLOSE_BUY)
 )
)
