(START )
(IF (AND (> (SValue CLOSE S_CURRENT CurrentPeriod )
(SPValue HIGH S_PREVIOUS CurrentPeriod )
)
(> (SValue CLOSE S_CURRENT CurrentPeriod )
(SValue HIGH S_PREVIOUS CurrentPeriod )
)
(AndPS LOW S_DOWN CurrentPeriod )
)
(BUY )
)
(IF (AND (< (SValue CLOSE S_CURRENT CurrentPeriod )
(SPValue LOW S_PREVIOUS CurrentPeriod )
)
(< (SValue CLOSE S_CURRENT CurrentPeriod )
(SValue LOW S_PREVIOUS CurrentPeriod )
)
(AndPS HIGH S_UP CurrentPeriod )
)
(SELL )
)
(EXIT )
