#define volume_up(...) _volume_up(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _volume_up (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define volume_down(...) _volume_down(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _volume_down (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Trade_only_buy(...) _Trade_only_buy(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Trade_only_buy (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Trade_only_sell(...) _Trade_only_sell(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Trade_only_sell (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Trade_buy_profit_positif(...) _Trade_buy_profit_positif(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Trade_buy_profit_positif (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Trade_sell_profit_positif(...) _Trade_sell_profit_positif(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Trade_sell_profit_positif (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Trade_buy_and_sell(...) _Trade_buy_and_sell(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Trade_buy_and_sell (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule);
