(SETQ Bid_P (/ (abs (SValue PIVOT_POINT S_DISTANCE P_D1)
               )
               Point)
)
(IF (AND (< Bid_P 10)
     (NOT (AndS PIVOT_POINT S_CROSS_UP P_D1)
     )
     (NOT (AndS PIVOT_POINT S_CROSS_DOWN P_D1)
     )
    )
 (IF (AND (AndS PIVOT_POINT S_BELOW P_D1)
      (AndPS BAR S_BEAR P_D1)
      (AndS BAR S_BULL P_H1)
     )
  (START)
  (BUY)
 )
 (IF (AND (AndS PIVOT_POINT S_ABOVE P_D1)
      (AndPS BAR S_BULL P_D1)
      (AndS BAR S_BEAR P_H1)
     )
  (START)
  (SELL)
 )
)
