/* ============================================================
STRATEGY : FRACTAL_CHANGED_H4
RULE : F
=============================================================*/

void R_RULE (F)
{

//------------------------------BUYSELL ENGINE ------------------------------

//--------------PROPERTIES ------------------------------

	Set_Rule(OP_BUYSELL, T_DIRECTION, R_F, P_SIGNAL, D_ANY);
	Set_Rule(OP_BUYSELL, T_DIRECTIONTYPE, R_F, P_SIGNAL, DT_MINMAX);
	Set_Rule(OP_BUYSELL, T_RECOVERYMODE, R_F, P_SIGNAL, M_K);
	Set_Rule(OP_BUYSELL, T_RECOVERYVALUE, R_F, P_SIGNAL, 50);
	Set_Rule(OP_BUYSELL, T_ILOT, R_F, P_SIGNAL, 0.3);
	Set_Rule(OP_BUYSELL, T_MAXLOT, R_F, P_SIGNAL, 6);
	Set_Rule(OP_BUYSELL, T_MAXCOUNT, R_F, P_SIGNAL, 1);
	Set_Rule(OP_BUYSELL, T_KEEPBUYSELL, R_F, P_SIGNAL, false);
	Set_Rule(OP_BUYSELL, T_EXITMODE, R_F, P_SIGNAL, EM_EXITANY);
	Set_Rule(OP_BUYSELL, T_PIPSTEP, R_F, P_SIGNAL, 30);
	Set_Rule(OP_BUYSELL, T_TIMESTEP, R_F, P_SIGNAL, 10);
	Set_Rule(OP_BUYSELL, T_MAXTIME, R_F, P_SIGNAL, 0);
	Set_Rule(OP_BUYSELL, T_HEDGEMAGNITUDE, R_F, P_SIGNAL, 1);
	Set_Rule(OP_BUYSELL, T_BUYTS, R_F, P_SIGNAL, 0);
	Set_Rule(OP_BUYSELL, T_BUYTP, R_F, P_SIGNAL, 0);
	Set_Rule(OP_BUYSELL, T_BUYSL, R_F, P_SIGNAL, 0);
	Set_Rule(OP_BUYSELL, T_SELLTS, R_F, P_SIGNAL, 0);
	Set_Rule(OP_BUYSELL, T_SELLTP, R_F, P_SIGNAL, 0);
	Set_Rule(OP_BUYSELL, T_SELLSL, R_F, P_SIGNAL, 0);
	Set_Rule(OP_BUYSELL, T_TS, R_F, P_SIGNAL, 0);
	Set_Rule(OP_BUYSELL, T_TP, R_F, P_SIGNAL, 0);
	Set_Rule(OP_BUYSELL, T_SL, R_F, P_SIGNAL, 0);
	Set_Rule(OP_BUYSELL, T_BUYLOTTS, R_F, P_SIGNAL, 20);
	Set_Rule(OP_BUYSELL, T_BUYLOTTP, R_F, P_SIGNAL, 0);
	Set_Rule(OP_BUYSELL, T_BUYLOTSL, R_F, P_SIGNAL, 50);
	Set_Rule(OP_EXIT_BUY, T_MINPROFIT, R_F, P_SIGNAL, 0);
	Set_Rule(OP_BUYSELL, T_SELLLOTTS, R_F, P_SIGNAL, 20);
	Set_Rule(OP_BUYSELL, T_SELLLOTTP, R_F, P_SIGNAL, 0);
	Set_Rule(OP_BUYSELL, T_SELLLOTSL, R_F, P_SIGNAL, 50);
	Set_Rule(OP_EXIT_SELL, T_MINPROFIT, R_F, P_SIGNAL, 0);
	Set_Rule(OP_EXIT, T_MINPROFIT, R_F, P_SIGNAL, 100);

//--------------END PROPERTIES ------------------------------


if ((AndS(UPFRACTAL, S_DOWN, P_H4) && AndS(UPFRACTAL, S_CHANGED, P_H4) && AndS(DOWNFRACTAL, S_DOWN, P_H4)))

{ Set_Rule(OP_BUYSELL, T_START, R_F, P_SIGNAL);Set_Rule(OP_SELL, T_STATUS, R_F, P_SIGNAL);}

if ((AndS(DOWNFRACTAL, S_CHANGED, P_H4) && AndS(UPFRACTAL, S_UP, P_H4) && AndS(DOWNFRACTAL, S_UP, P_H4)))

{ Set_Rule(OP_BUYSELL, T_START, R_F, P_SIGNAL);Set_Rule(OP_BUY, T_STATUS, R_F, P_SIGNAL);}
Set_Rule(OP_EXIT, T_STATUS, R_F, P_SIGNAL);}

