(SETQ Distance_From_High (abs (/ (SValue PIVOT_HIGH S_DISTANCE P_D1)
                                 Point)
                         )
)
(IF (AND (OR (AndPS BAR S_BULL_HAMMER P_D1)
          (AndPS BAR S_BULL_HAMMER1 P_D1)
          (AndPS BAR S_BULL_HAMMER2 P_D1)
          (AndPS BAR S_BULL P_D1)
         )
     (NOT (AndS PIVOT_HIGH S_CROSS_UP P_D1)
     )
     (AndS PIVOT_HIGH S_BELOW P_D1)
     (<= Distance_From_High 15)
    )
 (START)
 (BUY)
)
