(SETQ Distance_From_Low (abs (/ (SValue PIVOT_LOW S_DISTANCE P_D1)
                                Point)
                        )
)
(IF (AND (OR (AndPS BAR S_BEAR_SHOOTING_STAR P_D1)
          (AndPS BAR S_BEAR_SHOOTING_STAR1 P_D1)
          (AndPS BAR S_BEAR_SHOOTING_STAR2 P_D1)
          (AndPS BAR S_BEAR P_D1)
         )
     (NOT (AndS PIVOT_LOW S_CROSS_DOWN P_D1)
     )
     (AndS PIVOT_LOW S_ABOVE P_D1)
     (<= Distance_From_Low 15)
    )
 (START)
 (SELL)
)
