(SETQ Distance_From_Low (abs (/ (SValue PIVOT_LOW S_DISTANCE P_D1)
                                Point)
                        )
)
(IF (AND (NOT (AndS PIVOT_LOW S_CROSS_DOWN P_D1)
         )
     (<= Distance_From_Low 15)
     (AndPS BAR S_BEAR P_H1 )
    )
 (START)
 (SELL)
)
