#define Total_NbrTrades_0(...) _Total_NbrTrades_0(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Total_NbrTrades_0 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Engulfing_BULL_H1_H4_D1(...) _Engulfing_BULL_H1_H4_D1(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Engulfing_BULL_H1_H4_D1 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Engulfing_BEAR_H1_H4_D1(...) _Engulfing_BEAR_H1_H4_D1(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Engulfing_BEAR_H1_H4_D1 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Momentum_BULL(...) _Momentum_BULL(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Momentum_BULL (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Momentum_BEAR(...) _Momentum_BEAR(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Momentum_BEAR (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Velocity_Bear(...) _Velocity_Bear(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Velocity_Bear (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Velocity_Bull(...) _Velocity_Bull(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Velocity_Bull (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Trades_Sell_And_Buy(...) _Trades_Sell_And_Buy(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Trades_Sell_And_Buy (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Prev_SS_D1(...) _Prev_SS_D1(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Prev_SS_D1 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Prev_Hammer_D1(...) _Prev_Hammer_D1(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Prev_Hammer_D1 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Time_More_2340(...) _Time_More_2340(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Time_More_2340 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define CROSS_UP_CLOSE_D1_PREVIOUS_BULL(...) _CROSS_UP_CLOSE_D1_PREVIOUS_BULL(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _CROSS_UP_CLOSE_D1_PREVIOUS_BULL (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define CROSS_DOWN_CLOSE_D1_PREVIOUS_BEAR(...) _CROSS_DOWN_CLOSE_D1_PREVIOUS_BEAR(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _CROSS_DOWN_CLOSE_D1_PREVIOUS_BEAR (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define REVERSE_UP_CLOSE(...) _REVERSE_UP_CLOSE(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _REVERSE_UP_CLOSE (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define angle_up_15_10(...) _angle_up_15_10(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _angle_up_15_10 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define angle_down_15_10(...) _angle_down_15_10(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _angle_down_15_10 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Trade_no(...) _Trade_no(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Trade_no (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Trade_no1(...) _Trade_no1(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Trade_no1 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Trade_no12(...) _Trade_no12(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Trade_no12 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Trade_no123(...) _Trade_no123(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Trade_no123 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Trade_no1234(...) _Trade_no1234(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Trade_no1234 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
