(SETQ Distance_From_Low (/ (SValue PIVOT_SUPPORT S_DISTANCE P_D1)
                           Point)
)
(IF (AND (NOT (AndS PIVOT_SUPPORT S_CROSS_DOWN P_D1)
         )
     (<= Distance_From_Low 8)
     (AndPS BAR S_BEAR P_H1)
    )
 (START)
 (SELL)
)
