(IF (AND (AndS RSI_2 S_OVERSOLD P_H1)
     (AndS MA_200 S_ABOVE P_H1)
     (AndS Arrow S_BULL P_M1)
     (NOT (AndS VELOCITY S_OVERSOLD P_M5)
     )
    )
 (START)
 (BUY)
)
(IF (AND (AndS RSI_2 S_OVERBOUGHT P_H1)
     (AndS MA_200 S_BELOW P_H1)
     (AndS Arrow S_BEAR P_M1)
     (NOT (AndS VELOCITY S_OVERBOUGHT P_M5)
     )
    )
 (START)
 (SELL)
)
