(SETQ phigh (SValue HIGH S_PREVIOUS P_H1)
)
(SETQ plow (SValue LOW S_PREVIOUS P_H1)
)
(SETQ bSL plow)
(SETQ sSL phigh)
(IF (AND (Prev_Bear_PinBar)
     (Prev_Bar_Intersect_Upper_Pivots)
    )
 (START)
 (SELL)
)
(IF (AND (Prev_Bull_PinBar)
     (Prev_Bar_Intersect_Lower_Pivots)
    )
 (START)
 (BUY)
)
