(SETQ Distance_From_High (abs (/ (SValue PIVOT_HIGH S_DISTANCE P_D1 )
Point )
)
)
(IF (AND (NOT (AndS PIVOT_HIGH S_CROSS_UP P_D1 )
)
(AndS PIVOT_HIGH S_BELOW P_D1 )
(<= Distance_From_High 10 )
)
(START )
(BUY )
)
