(SETQ Distance_From_Pivot (abs (/ (SValue PIVOT_POINT S_DISTANCE P_D1 )
Point )
)
)
(IF (AND (AndS PIVOT_POINT S_BELOW P_D1 )
(NOT (AndS PIVOT_POINT S_CROSS_UP P_D1 )
)
(NOT (AndS PIVOT_POINT S_CROSS_DOWN P_D1 )
)
(<= Distance_From_Pivot 10 )
)
(START )
(BUY )
)
(IF (AND (AndS PIVOT_POINT S_ABOVE P_D1 )
(NOT (AndS PIVOT_POINT S_CROSS_DOWN P_D1 )
)
(NOT (AndS PIVOT_POINT S_CROSS_UP P_D1 )
)
(<= Distance_From_Pivot 10 )
)
(START )
(SELL )
)
