#define Prev_Narrow_day(...) _Prev_Narrow_day(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Prev_Narrow_day (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Breakout_Big_Candle_M15_Bull(...) _Breakout_Big_Candle_M15_Bull(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Breakout_Big_Candle_M15_Bull (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Breakout_Big_Candle_M15_Bear(...) _Breakout_Big_Candle_M15_Bear(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Breakout_Big_Candle_M15_Bear (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Trade_no(...) _Trade_no(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Trade_no (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define velocity_up(...) _velocity_up(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _velocity_up (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define velocity_down(...) _velocity_down(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _velocity_down (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define volume_up(...) _volume_up(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _volume_up (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Momentum_is_bull(...) _Momentum_is_bull(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Momentum_is_bull (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Momentum_is_bear(...) _Momentum_is_bear(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Momentum_is_bear (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define volume_down(...) _volume_down(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _volume_down (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Trade_only_buy(...) _Trade_only_buy(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Trade_only_buy (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Trade_only_sell(...) _Trade_only_sell(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Trade_only_sell (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Trade_buy_profit_positif(...) _Trade_buy_profit_positif(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Trade_buy_profit_positif (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Trade_sell_profit_positif(...) _Trade_sell_profit_positif(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Trade_sell_profit_positif (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Trade_buy_and_sell(...) _Trade_buy_and_sell(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Trade_buy_and_sell (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define RSI_20_HEIKEN_BULL(...) _RSI_20_HEIKEN_BULL(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _RSI_20_HEIKEN_BULL (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define RSI_20_HEIKEN_BEAR(...) _RSI_20_HEIKEN_BEAR(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _RSI_20_HEIKEN_BEAR (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define CROSS_DOWN_CLOSE_PREVIOUS_BEAR(...) _CROSS_DOWN_CLOSE_PREVIOUS_BEAR(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _CROSS_DOWN_CLOSE_PREVIOUS_BEAR (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define CROSS_UP_CLOSE_PREVIOUS_BULL(...) _CROSS_UP_CLOSE_PREVIOUS_BULL(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _CROSS_UP_CLOSE_PREVIOUS_BULL (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Pivots_Alert(...) _Pivots_Alert(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Pivots_Alert (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Pivots_Touch(...) _Pivots_Touch(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Pivots_Touch (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Candle_Buy_Entry_H4(...) _Candle_Buy_Entry_H4(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Candle_Buy_Entry_H4 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Candle_Sell_Entry_H4(...) _Candle_Sell_Entry_H4(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Candle_Sell_Entry_H4 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Candle_Buy_Exit_H4(...) _Candle_Buy_Exit_H4(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Candle_Buy_Exit_H4 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Candle_Sell_Exit_H4(...) _Candle_Sell_Exit_H4(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Candle_Sell_Exit_H4 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Candle_Buy_Entry_H1(...) _Candle_Buy_Entry_H1(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Candle_Buy_Entry_H1 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Candle_Sell_Entry_H1(...) _Candle_Sell_Entry_H1(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Candle_Sell_Entry_H1 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Candle_Buy_Exit_H1(...) _Candle_Buy_Exit_H1(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Candle_Buy_Exit_H1 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Candle_Sell_Exit_H1(...) _Candle_Sell_Exit_H1(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Candle_Sell_Exit_H1 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Candle_Buy_Entry_M30(...) _Candle_Buy_Entry_M30(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Candle_Buy_Entry_M30 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Candle_Sell_Entry_M30(...) _Candle_Sell_Entry_M30(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Candle_Sell_Entry_M30 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Candle_Buy_Exit_M30(...) _Candle_Buy_Exit_M30(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Candle_Buy_Exit_M30 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Candle_Sell_Exit_M30(...) _Candle_Sell_Exit_M30(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Candle_Sell_Exit_M30 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Trade_Buy_Candle(...) _Trade_Buy_Candle(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Trade_Buy_Candle (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define FractalUp_Approaching_H1(...) _FractalUp_Approaching_H1(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _FractalUp_Approaching_H1 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Candle_Buy_Entry_D1(...) _Candle_Buy_Entry_D1(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Candle_Buy_Entry_D1 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Candle_Buy_Exit_D1(...) _Candle_Buy_Exit_D1(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Candle_Buy_Exit_D1 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Candle_Sell_Entry_D1(...) _Candle_Sell_Entry_D1(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Candle_Sell_Entry_D1 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Candle_Sell_Exit_D1(...) _Candle_Sell_Exit_D1(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Candle_Sell_Exit_D1 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define FractalDown_Approaching_H1(...) _FractalDown_Approaching_H1(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _FractalDown_Approaching_H1 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define FractalUp_Approaching_H4(...) _FractalUp_Approaching_H4(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _FractalUp_Approaching_H4 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define FractalDown_Approaching_H4(...) _FractalDown_Approaching_H4(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _FractalDown_Approaching_H4 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define FractalDown_Approaching_D1(...) _FractalDown_Approaching_D1(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _FractalDown_Approaching_D1 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define FractalUp_Approaching_D1(...) _FractalUp_Approaching_D1(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _FractalUp_Approaching_D1 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define FractalUp_Approaching(...) _FractalUp_Approaching(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _FractalUp_Approaching (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define FractalDown_Approaching(...) _FractalDown_Approaching(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _FractalDown_Approaching (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Gap_Down_D1(...) _Gap_Down_D1(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Gap_Down_D1 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Gap_Up_D1(...) _Gap_Up_D1(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Gap_Up_D1 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Candle_Bull_Changed_H1(...) _Candle_Bull_Changed_H1(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Candle_Bull_Changed_H1 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Candle_Bear_Changed_H1(...) _Candle_Bear_Changed_H1(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Candle_Bear_Changed_H1 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Pivot_Up_Approaching_D1(...) _Pivot_Up_Approaching_D1(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Pivot_Up_Approaching_D1 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Pivot_Down_Approaching_D1(...) _Pivot_Down_Approaching_D1(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Pivot_Down_Approaching_D1 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Trade_Buy_OnBar_H1(...) _Trade_Buy_OnBar_H1(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Trade_Buy_OnBar_H1 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Trade_Sell_OnBar_H1(...) _Trade_Sell_OnBar_H1(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Trade_Sell_OnBar_H1 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Candle_Min_Size(...) _Candle_Min_Size(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Candle_Min_Size (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define ShouldExit(...) _ShouldExit(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _ShouldExit (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define ShouldStart(...) _ShouldStart(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _ShouldStart (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Fractal_Up_Zone(...) _Fractal_Up_Zone(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Fractal_Up_Zone (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Fractal_Down_Zone(...) _Fractal_Down_Zone(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Fractal_Down_Zone (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Pivot_Down_Zone(...) _Pivot_Down_Zone(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Pivot_Down_Zone (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Pivot_Up_Zone(...) _Pivot_Up_Zone(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Pivot_Up_Zone (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Candle_Hammer_D1(...) _Candle_Hammer_D1(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Candle_Hammer_D1 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Candle_ShootingStar_D1(...) _Candle_ShootingStar_D1(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Candle_ShootingStar_D1 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Candle_Hammer_H1(...) _Candle_Hammer_H1(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Candle_Hammer_H1 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Candle_ShootingStar_H1(...) _Candle_ShootingStar_H1(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Candle_ShootingStar_H1 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Prev_Bear_PinBar(...) _Prev_Bear_PinBar(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Prev_Bear_PinBar (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Prev_Bull_PinBar(...) _Prev_Bull_PinBar(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Prev_Bull_PinBar (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Prev_Bar_Intersect_Upper_Pivots(...) _Prev_Bar_Intersect_Upper_Pivots(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Prev_Bar_Intersect_Upper_Pivots (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Prev_Bar_Intersect_Lower_Pivots(...) _Prev_Bar_Intersect_Lower_Pivots(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Prev_Bar_Intersect_Lower_Pivots (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Engulfing_BEAR_H1_H4_D1(...) _Engulfing_BEAR_H1_H4_D1(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Engulfing_BEAR_H1_H4_D1 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Engulfing_BULL_H1_H4_D1(...) _Engulfing_BULL_H1_H4_D1(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Engulfing_BULL_H1_H4_D1 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Momentum_BEAR(...) _Momentum_BEAR(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Momentum_BEAR (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Momentum_BULL(...) _Momentum_BULL(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Momentum_BULL (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Total_NbrTrades_0(...) _Total_NbrTrades_0(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Total_NbrTrades_0 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define Time_More_2340(...) _Time_More_2340(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _Time_More_2340 (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define CROSS_DOWN_CLOSE_D1_PREVIOUS_BEAR(...) _CROSS_DOWN_CLOSE_D1_PREVIOUS_BEAR(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _CROSS_DOWN_CLOSE_D1_PREVIOUS_BEAR (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define CROSS_UP_CLOSE_D1_PREVIOUS_BULL(...) _CROSS_UP_CLOSE_D1_PREVIOUS_BULL(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern bool _CROSS_UP_CLOSE_D1_PREVIOUS_BULL (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule); 
#define FindClosestPivot(...) _FindClosestPivot(Ask, Bid, TimeCurrent, CurrentPeriod, Symbol, Point, Digits, SignalTab, SignalTabValue, SignalTabTime,SignalTabPrice, BeforeSignalTab, BeforeSignalTabValue, BeforeSignalTabTime,BeforeSignalTabPrice,BeforeSignalTickTab, RuleTab, RuleTabValue, BeforeRuleTab, BeforeRuleTabValue,  ##__VA_ARGS__)
extern double _FindClosestPivot  (double Ask, double Bid, datetime TimeCurrent, int CurrentPeriod, std::string Symbol, double Point, double Digits, int* SignalTab, double* SignalTabValue, datetime*	SignalTabTime, double* SignalTabPrice, int* BeforeSignalTab, double* BeforeSignalTabValue, datetime* BeforeSignalTabTime, double* BeforeSignalTabPrice,int* BeforeSignalTickTab, int* RuleTab, double* RuleTabValue, int* BeforeRuleTab, double* BeforeRuleTabValue, int Operation, int Rule, int way, double value, double min);