//---------------------------------------------------- ICONS AWESOME    ----------------------------------------  
const icon_remove     = 'fas fa-trash';
const icon_copy       = 'far fa-copy';
const icon_cut        = 'fas fa-cut';
const icon_rename     = 'far fa-edit sb_baricon';
const icon_paste      = 'fas fa-paste';
const icon_trash      = 'far fa-trash-alt';
const icon_search     = 'fa fa-search';

const icon_more       = 'fas fa-ellipsis-h';

const icon_indicator  = 'far fa-chart-bar';
const icon_signal     = 'fas fa-signal'; 
const icon_condition  = 'fas fa-gavel'; 
const icon_project    = 'fas fa-project-diagram';
const icon_chart      = 'fas fa-chart-line';
const icon_chart_bar  = 'fas fa-chart-bar';
const icon_chart_area = 'fas fa-chart-area';
const icon_strategy   = 'fas fa-chess';
const icon_mt4expert  = 'fas fa-cogs';
const icon_film       = 'fas fa-film';
const icon_helper     = 'fas fa-info-circle';
const icon_automation = 'fas fa-cogs';
const icon_arrow_up   = 'fas fa-caret-up';
const icon_arrow_down = 'fas fa-caret-down';
const icon_arrow_right= 'fas fa-caret-right';
const icon_arrow_left = 'fas fa-caret-left';
const icon_market     = 'far fa-money-bill-alt';
const icon_news       = 'fas fa-calendar-alt';
const icon_alerts     = 'fa fa-bolt';
const icon_user       = 'fas fa-user';
const icon_toggle     = 'fas fa-align-left';
const icon_settings   = 'fa fa-cog';
const icon_caretdown  = 'fas fa-caret-down';
const icon_caretup    = 'fas fa-caret-up';
const icon_sort       = 'fas fa-sort';
const icon_maximize   = 'fas fa-expand-arrows-alt';
const icon_minimize   = 'fas fa-compress-arrows-alt';
const icon_times      = 'fas fa-times';
const icon_windowclose= 'far fa-window-close';
const icon_close      = 'fas fa-close';

const icon_s_caretright = 'fa-square-caret-right';
const icon_dice       = 'fas fa-dice';                                  
const icon_track      = 'fas fa-chess-knight';   
const icon_tradedesk  = 'fas fa-chalkboard';   
const icon_terminal   = 'fas fa-desktop';       
const icon_card       = 'far fa-credit-card';      
const icon_file       = 'fas fa-file';         
const icon_filealt    = 'fas fa-file-alt';
const icon_files      = 'far fa-clone';
const icon_folder     = 'far fa-folder';  
const icon_eye        = 'far fa-eye';
const icon_play       = 'fas fa-play';
const icon_stop       = 'fas fa-stop';
const icon_pause      = 'fas fa-pause';
const icon_forward    = 'fas fa-forward';
const icon_backward   = 'fas fa-backward';
const icon_repeat     = 'fas fa-repeat';
const icon_forwardstep = 'fas fa-forward-step';
const icon_backwardstep = 'fas fa-backward-step';
const icon_settings1   = 'far fa-sun';
const icon_graphic    = 'fas fa-sitemap';
const icon_split      = 'fas fa-grip-lines-vertical';
const icon_deploy     = 'fas fa-cloud-download-alt';
const icon_upload     = 'fas fa-upload';

const icon_download   = 'fas fa-download';
const icon_export     = 'fas fa-file-export';

const icon_compile    = 'fas fa-wrench';
const icon_plus       = 'fas fa-plus';
const icon_new        = 'fa fa-plus-circle';
const icon_sound      = 'fas fa-volume-off';
const icon_micro      = 'fas fa-microphone';

const icon_history    = 'fas fa-history';
const icon_inspect    = 'fas fa-glasses';
const icon_arrowright = 'fas fa-chevron-right';
const icon_arrowdown  = 'fas fa-chevron-down';
const icon_arrowleft  = 'fas fa-chevron-left';
const icon_arrowup    = 'fas fa-chevron-up';
const icon_check      = 'fa-solid fa-check';
const icon_save       = 'fas fa-save';
const icon_cancel     = 'fas fa-rotate-left';
const icon_home       = 'fas fa-house';
const icon_structure  = 'fas fa-folder-tree';
const icon_siteview   = 'fa-brands fa-connectdevelop';

const icon_manager    = 'fas fa-layer-group';
const icon_site       = 'fas fa-building';
const icon_machine    = 'fas fa-desktop';
const icon_application= 'fas fa-tasks'
const icon_database   = 'fas fa-database';
const icon_journal    = 'far fa-file-lines';
const icon_queue      = 'far fa-envelope';
const icon_connection = 'fas fa-circle-nodes';
const icon_record     = 'fas fa-record-vinyl';
//const icon_server     = 'fa-solid fa-server'
const icon_server     = 'bi bi-filetype-js';
const icon_language   = 'fas fa-language';
const icon_help       = 'fas fa-hands-helping';
const icon_thanks     = 'fas fa-fist-raised';
const icon_video      = 'fas fa-video';
const icon_comment    = 'fas fa-comment';
const icon_link       = 'fas fa-link';
const icon_grip       = 'fas fa-grip-lines';
const icon_swap       = 'fas fa-arrow-right-arrow-left';
const icon_ellipsis   = 'fas fa-ellipsis';
const icon_creditcard = 'fas fa-credit-card';
const icon_tags       = 'fas fa-tags';
const icon_tag        = 'fas fa-tag';
const icon_question   = 'far fa-circle-question';
const icon_pin        = 'fas fa-thumbtack';
const icon_shop       = 'fas fa-shop';
const icon_exchange   = 'fas fa-right-left';
const icon_visa       = 'fa-brands fa-cc-visa';

//const icon_anglesdown;
//const icon_anglesup;
//const icon_angledown;
//const icon_angleup;