(IF (AndS SUPPORT S_CROSS_DOWN CurrentPeriod )
(START )
(SELL )
)
(IF (AndS RESISTANCE S_CROSS_UP CurrentPeriod )
(START )
(BUY )
)
(SET T_BUYLOTTS (Pips (* (SValue ATR_14 S_CURRENT CurrentPeriod )
2 )
)
)
(SET T_SELLLOTTS (Pips (* (SValue ATR_14 S_CURRENT CurrentPeriod )
2 )
)
)
(IF (AND (= T_SELLNBRTRADE 0 )
(= T_BUYNBRTRADE 0 )
)
(EXIT )
)
